### ISSUE TITLE
Travis sends failure emails although github has green checkmark 

### ISSUE THREAD

**Issue by MartijnKaijser** [xbmc/addon-check#20] opened 2017-12-20 17:31 UTC

**Comment by Rechi** [comment] 2017-12-20 17:38
I think that is caused by the failing branches.
For PRs only the changed addons are checked to  not confuse the author (and us), for a branch run all addons are checked.

**Comment by Razzeee** [comment] 2017-12-20 17:48
That's correct @Rechi

**Comment by mzfr** [comment] 2018-02-16 09:20
@Razzeee Is this fixed? or is something still left to do? not really sure.

**Comment by Razzeee** [comment] 2018-02-23 21:34
Well the example code has been updated, but not sure if we changed that for the repos where we run this already.

**Comment by Razzeee** [comment] 2018-02-28 23:27
So I updated every known `.travis.yml` to include the email rule. So we should only get mails on changed status from now on. Let's see if it improves.

**Comment by mzfr** [comment] 2018-03-20 14:53
@Razzeee if everything seems ok with this then we should close this issue

**Comment by mzfr** [comment] 2018-08-12 12:59
@MartijnKaijser @Razzeee Are we still getting those emails ?

**Comment by Razzeee** [comment] 2018-08-12 20:03
@MartijnKaijser will just reopen it if it still bothers him

**Closed by Razzeee** 2018-08-12 20:03 UTC
